on:
  workflow_dispatch:
  push:
    branches: [ master, main ]
  #pull_request_target:
  #  branches: [ master, main ]

permissions: write-all

name: lint-code-style
jobs:
  lint-code-style:
    name: style linters
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version: ~1.20

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          github_token: "${{ secrets.IKEMEN_TOKEN }}"
          gofmt: true
          continue_on_error: false
          auto_fix: true
          commit_message: "style: fix code style issues with ${linter}"
          neutral_check_on_warning: true
